hash-format = "sha256"

[[files]]
file = "config/c2me.toml"
hash = "fee3dc4774bd4345a9c721927c4d614c298a49bd583a77f7b5d46d0816856f59"

[[files]]
file = "mods/additional-structures.pw.toml"
hash = "b7652939932ffd4a3205c67906a48eac67e3186b30842ebf4e6d43efdc64c776"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "2b66c02d4d4761a2a1ed805a391a9294ba29103182b86092423ca5c908421e8e"
metafile = true

[[files]]
file = "mods/axes-are-weapons.pw.toml"
hash = "7d3db5f37a91ed7af9ced5b72d9d14774498c5b4f398b2c06e1c05bd3f33db07"
metafile = true

[[files]]
file = "mods/betterleads.pw.toml"
hash = "3ecbc3e344d8da1ab6cda12e4bcd446ee4ee62525b729a240c381ee998722d1c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "d4e882278d0a8d863a069df56f6e473e81e79c48f8cc6e700a56f297847178ca"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b6348f94ec939f563285dc96683e61da8fc17ab2f2897be2751fa24789513691"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "204b3eb115e418bdad4f5f2e8ef49f0c8b8f10ad062ca10e05e1e8cde4de45ab"
metafile = true

[[files]]
file = "mods/couplings.pw.toml"
hash = "47e796fa0168407d6bf12e3aac6cf29881960df43ed21f844ab34ac891ee0730"
metafile = true

[[files]]
file = "mods/death-backup.pw.toml"
hash = "abe0735af4a121e00bbf54b00f350f8cf09fd1ad69687bbd34a3f346a511baa5"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "4ba45966a267b774f5d83442c3c43d740f55e11a910e117e50c046b4f77b5c66"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "b9cca3d3bb4ff0d6cd2f397e2baf40235f869bb156970d8549448d43ba3d8229"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "3a93a5b987d89b3ce4208d1e31b3a5636fc6363ff33896f5a7ad8961df94a236"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "ff4a66502e802341a84fbb8eceed65156b14436769b1f7e27a68b22fb59c1dae"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
hash = "b5fa39db5c13454ebc82cfc76da7fa33ccaa389986f407a033c5c9675633f00c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "03e174cf691b52da20bd973b955fae6f3720d3d2120f9d6cc1de5fdf3180013c"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "129bb8b135edc60038f021b693f5b88a0067b722f326e0d6067112243774289b"
metafile = true

[[files]]
file = "mods/image2map.pw.toml"
hash = "5ba86432dafed77442fbc2ea11db62a15b1919e47656fda26c393b4ee62f6eca"
metafile = true

[[files]]
file = "mods/immersive-structures.pw.toml"
hash = "87184da0fbda69dd2d209f9597beca5241893eb32e3e3d07356d1be3afa496b8"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "fb895dcf5858adba539fa4afbaf183308e10e23c9e5cb7f619e5ffa1281781cd"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "4a37864ebe44ddf66f7a127683adc76515d3dc97f8d8dba6fe362c43a1f39464"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "d7c03a9a61a81693732b6ae275f63ee63aa97def2e511be48b740e03c4f34a17"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "84defc8f8116d5c0e4210934ed1f555641a1db71b767fa4beddee21c47118868"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "879f42a9c6ede67873e773764319cc52105db1c5bfdd540878c9a28eaa0c5561"
metafile = true

[[files]]
file = "mods/mob-captains.pw.toml"
hash = "4da733514ca3601f7a773759a6fc2ced2cc10d3d1f07b602d7b572da53a95849"
metafile = true

[[files]]
file = "mods/no-rocket-boosting.pw.toml"
hash = "cb4b300e01390838a8cfc70da9bea29e8715d599d7e18704a9aadf4c4b5a85a6"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "be14d9e96b119117afce2c77700bcae11d21cdc276471b54bbf3cf89496e2060"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "8cd8f7a7a486065f4fafb0f841bc231b2542e13fe0795c8cb3af1735a83da013"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "31b3bcbde9677f9fc1006aab482e6f43b7552146359cc4ef363e30a237d1d12b"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "b5a0689c8ca4d98adb7dfe35df4bc6a1dceac5c4b792e5fbb0ad5290991e2684"
metafile = true

[[files]]
file = "mods/snow-under-trees-remastered.pw.toml"
hash = "3e296e373e17d6c4d9e8a914d07b841fcfa4faaefcb1ac00aafd4ac9d71e72aa"
metafile = true

[[files]]
file = "mods/spawn-animations.pw.toml"
hash = "e0abd290de019a8918b8f7f68bdc7a63ed43921082a8f70ef6cba99bf3582784"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "218f67d6bcaae849582618cd3e5eb1d4cac0fd6045115f64340620300e160c11"
metafile = true

[[files]]
file = "mods/tabtps.pw.toml"
hash = "715238672c12a843ccaee2b423314e78f28f38e526822215c1b398877c51fbc5"
metafile = true

[[files]]
file = "mods/ultris.pw.toml"
hash = "2ce4328079fe4ccac39d71bf6a5f9933d3b9fa742f993913c04d5bc86f84fe7b"
metafile = true

[[files]]
file = "mods/vanilla-refresh.pw.toml"
hash = "3dcaf68f7bcbdd4fe25af1ca2400a10952aae1514e87ff304fef91cfad271566"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "2008716fdfef554660ce44659a3a42acd673a5391af2d4bd94f40654f1f60a1d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true
